Add relationship predicates (anyIn and anyEquals) and stringEquals
3Squared/PeakCoreData pull request #13
Opened 2019-07-22 15:24 UTC by djyates

Additional predicate initialisers and unit tests, including:

`NSPredicate(format: "ANY %K == %@", argumentArray: [keyPath, value])`
`NSPredicate(format: "ANY %K IN %@", argumentArray: [keyPath, value])`
`NSPredicate(format: "SELF ==[cd] %@", argumentArray: [string])`

Also added a flag to allow case sensitive comparison of strings

2019-07-23 07:51 UTC, BendyWalker requested changes
Apart from the typos, these changes look good. Presumably the case insensitive stuff could be used to indirectly help with #12?

2019-07-23 07:51 UTC, BendyWalker commented on PeakCoreDataTests/PredicateTests.swift
> +    func testStringBeginsWithCaseSsensitive() {
Typo 🐍

2019-07-23 07:51 UTC, BendyWalker commented on PeakCoreDataTests/PredicateTests.swift
> +    func testStringEqualsCaseSsensitive() {
Typo 🐍

2019-07-23 07:51 UTC, BendyWalker commented on PeakCoreDataTests/PredicateTests.swift
> +    func testStringEndsWithCaseSsensitive() {
Typo 🐍

2019-07-23 08:43 UTC, BendyWalker approved these changes

2019-07-24 13:51 UTC, SamTTaylor approved these changes

2019-07-24 14:04 UTC, blork approved these changes

2019-07-24 14:09 UTC, merged